package main

import (
	"testing"
)

func TestLinkedList(t *testing.T) {
	t.Run("Test Linked List", func(t *testing.T) {
		list := LinkedList{}
		assertTrue(t, list.IsEmpty())
		assertEqual(t, list.Len(), 0)
		list.InsertFront("hello")
		assertFalse(t, list.IsEmpty())
		assertEqual(t, list.head.content, "hello")
		assertEqual(t, list.tail.content, "hello")
		assertEqual(t, list.Len(), 1)
		list.InsertFront("world")
		assertEqual(t, list.head.content, "world")
		assertEqual(t, list.Len(), 2)
		value, err := list.RemoveFront()
		assertEqual(t, err, nil)
		assertEqual(t, value, "world")
		assertEqual(t, list.Len(), 1)
		value, err = list.RemoveFront()
		assertEqual(t, err, nil)
		assertEqual(t, value, "hello")
		assertEqual(t, list.Len(), 0)
		value, err = list.RemoveFront()
		assertEqual(t, err.Error(), "Can not remove from empty list")
		assertEqual(t, value, nil)
		assertEqual(t, list.Len(), 0)
		list.InsertBack(3.14)
		assertEqual(t, list.tail.content, 3.14)
		assertEqual(t, list.head.content, 3.14)
		assertEqual(t, list.Len(), 1)
		list.InsertBack("Maker")
		assertEqual(t, list.tail.content, "Maker")
		assertEqual(t, list.head.content, 3.14)
		assertEqual(t, list.Len(), 2)
		list.InsertBack(8)
		assertEqual(t, list.tail.content, 8)
		assertEqual(t, list.head.content, 3.14)
		assertEqual(t, list.Len(), 3)
		value, err = list.RemoveBack()
		assertEqual(t, err, nil)
		assertEqual(t, value, 8)
		assertEqual(t, list.Len(), 2)
		value, err = list.RemoveBack()
		assertEqual(t, err, nil)
		assertEqual(t, value, "Maker")
		assertEqual(t, list.Len(), 1)
		value, err = list.RemoveBack()
		assertEqual(t, err, nil)
		assertEqual(t, value, 3.14)
		assertEqual(t, list.Len(), 0)
		value, err = list.RemoveBack()
		assertEqual(t, err.Error(), "Can not remove from empty list")
		assertEqual(t, value, nil)
		assertEqual(t, list.Len(), 0)
	})
}
