#+TITLE: Building a module in Go

This directory just contains Notes and sample programs I made while working
through the "[[https://www.udemy.com/course/building-a-module-in-go-golang/][Building a module in Go]]" course on Udemy.

* Programs:
  This course is going to build out a go module similar to:
  https://github.com/tsawler/toolbox. This directory will contain code for the
  module itself and multiple applications that will use the module. I suggest
  looking through the module first and then looking the applications in the
  order listed:
  - 1. :: [[./tookit/][Module]]
  - 2. :: [[./app/][Application]]
  - 3. :: [[./app-upload/][Application Upload]]
  - 4. :: [[./app-dir/][Application Directory]]
  - 5. :: [[./app-slug/][Application Slug]]
  - 6. :: [[./app-download/][Application Download]]
  - 7. :: [[./app-json/][Application JSON]]
  - 8. :: [[./api-test/][Final Test]]

* Notes:
  In Go 1.18 the Go team added a feature called workspaces. This features allows
  you to generate a file called ~go.work~, which will allow you to work with
  multiple modules simultaneously. You can see a ~go.work~ file in this
  directory. This was generated with the following command:
  #+begin_src shell
    go work init toolkit app
  #+end_src

  New applications can be added to the ~go.work~ file by using:
  #+begin_src shell
    go work use <app name>
  #+end_src

  More info can be found on workspaces here:
  - https://go.dev/blog/get-familiar-with-workspaces
  - https://go.dev/doc/tutorial/workspaces

  The Go team has put together a guide on how modules are going to be handled
  going forward with regards to semantic versioning of modules:
  https://go.dev/blog/v2-go-modules.
